apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: chat-client
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: chat-client
                port:
                  number: 3000
