apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chat-app.fullname" . }}-secret
  labels:
    {{- include "chat-app.labels" . | nindent 4 }}
type: Opaque
data:
  # MongoDB credentials
  {{- if .Values.mongodb.enabled }}
  {{- if .Values.mongodb.auth.username }}
  MONGODB_USERNAME: {{ .Values.mongodb.auth.username | b64enc | quote }}
  {{- end }}
  {{- if .Values.mongodb.auth.password }}
  MONGODB_PASSWORD: {{ .Values.mongodb.auth.password | b64enc | quote }}
  {{- end }}
  {{- else }}
  {{- if .Values.externalMongodb.username }}
  MONGODB_USERNAME: {{ .Values.externalMongodb.username | b64enc | quote }}
  {{- end }}
  {{- if .Values.externalMongodb.password }}
  MONGODB_PASSWORD: {{ .Values.externalMongodb.password | b64enc | quote }}
  {{- end }}
  {{- end }}
  
  # Redis password (if authentication is enabled)
  {{- if .Values.redis.enabled }}
  {{- if .Values.redis.auth.enabled }}
  {{- if .Values.redis.auth.password }}
  REDIS_PASSWORD: {{ .Values.redis.auth.password | b64enc | quote }}
  {{- end }}
  {{- end }}
  {{- else }}
  {{- if .Values.externalRedis.password }}
  REDIS_PASSWORD: {{ .Values.externalRedis.password | b64enc | quote }}
  {{- end }}
  {{- end }}
  
  # JWT Secret for session management
  {{- if .Values.security.jwtSecret }}
  JWT_SECRET: {{ .Values.security.jwtSecret | b64enc | quote }}
  {{- else }}
  JWT_SECRET: {{ randAlphaNum 32 | b64enc | quote }}
  {{- end }}
  
  # Session secret for Express sessions
  {{- if .Values.security.sessionSecret }}
  SESSION_SECRET: {{ .Values.security.sessionSecret | b64enc | quote }}
  {{- else }}
  SESSION_SECRET: {{ randAlphaNum 32 | b64enc | quote }}
  {{- end }}
  
  # Additional secrets
  {{- range $key, $value := .Values.global.extraSecrets }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
