apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatter-server
  namespace: default
  labels:
    app: chatter-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: chatter-server
  template:
    metadata:
      labels:
        app: chatter-server
    spec:
      containers:
      - name: chatter-server
        image: chatter-server:latest  # Replace with your actual image
        imagePullPolicy: Never  # Use local image, don't pull from registry
        ports:
        - containerPort: 8000
          protocol: TCP
        env:
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: chatter-server-config
              key: PORT
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: chatter-server-config
              key: NODE_ENV
        - name: MONGODB_URI
          valueFrom:
            secretKeyRef:
              name: chatter-server-secrets
              key: MONGODB_URI
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: chatter-server-secrets
              key: JWT_SECRET
        - name: GOOGLE_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: chatter-server-secrets
              key: GOOGLE_CLIENT_ID
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        imagePullPolicy: Always
      restartPolicy: Always
