
# MongoDB and NATS subcharts
nats:
  enabled: true
  replicaCount: 1
  auth:
    enabled: false

# mongodb:
#   enabled: true
#   architecture: standalone
#   auth:
#     enabled: false

server:
  image:
    repository: ashu001/server
    tag: latest
    pullPolicy: Always
  port: 8000
  replicaCount: 3 # Increase to 3 for HA
  mongodbUri: ""
  natsUrl: "nats://chat-server-nats:4222" # Ensure NATS is accessible to all pods
  jwtSecretKey: "THIS_IS_A_JWT_SECRET_KEY"
  serverId: "{{ .Pod.Name }}"
  nodeEnv: "development"