services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - MONGODB=mongodb://mongodb:27017
      - DB_NAME=chatter
    depends_on:
      - mongodb
    # volumes:
    #   - .:/app
    networks:
      - chatter-network

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - chatter-network

volumes:
  mongodb_data:

networks:
  chatter-network:
    driver: bridge 