apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-server
  labels:
    app: chat-server
spec:
  replicas: {{ .Values.server.replicaCount }}
  selector:
    matchLabels:
      app: chat-server
  template:
    metadata:
      labels:
        app: chat-server
    spec:
      containers:
        - name: server
          image: "{{ .Values.server.image.repository }}:{{ .Values.server.image.tag }}"
          imagePullPolicy: {{ .Values.server.image.pullPolicy | default "IfNotPresent" }}
          ports:
            - containerPort: 8000
          env:
            - name: PORT
              value: "8000"
            - name: NODE_ENV
              value: {{ .Values.server.nodeEnv | default "development" | quote }}
            - name: MONGODB_URI
              value: {{ .Values.server.mongodbUri | default "mongodb://chat-server-mongodb:27017/chatter" | quote }}
            - name: NATS_URL
              value: {{ .Values.server.natsUrl | default "nats://chat-server-nats:4222" | quote }}
            - name: JWT_SECRET_KEY
              value: {{ .Values.server.jwtSecretKey | quote }}
            - name: SERVER_ID
              value: {{ .Values.server.serverId | quote }}
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "1000m"
