apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: chat-server
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: chat-server
                port:
                  number: 8000
